apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connectentrepreneurs-ingress
  namespace: connectentrepreneurs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: connectentrepreneurs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backoffice
            port:
              number: 80
